services:
  binternet:
    image: ghcr.io/ahwxorg/binternet:latest
    container_name: binternet
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - "8087:8080"
