version: 2
updates:
  - package-ecosystem: "docker"
    # This recursive search is the standard for monorepos/multiple stacks
    directory: "/" 
    schedule:
      interval: "weekly"
    # Grouping prevents 20 PRs for the same image update
    groups:
      docker-images:
        patterns:
          - "*"
