name: myspeed
services:
  myspeed:
    container_name: myspeed
    image: germannewsmaker/myspeed
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5216
        published: "5216"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/stacks/myspeed
        target: /myspeed/data
        bind:
          create_host_path: true
networks:
  default:
    name: myspeed_default
