services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:11
    container_name: cobalt
    restart: unless-stopped
    init: true
    read_only: true
    environment:
      - API_URL=http://160.30.5.117:9000
    ports:
      - "9000:9000"
