services:
  umbrel:
    image: dockurr/umbrel
    container_name: umbrel
    restart: unless-stopped
    pid: host
    stop_grace_period: 1m
    ports:
      - "8082:80"
    volumes:
      - /opt/stacks/umbrel:/data
      - /var/run/docker.sock:/var/run/docker.sock
