version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/stacks/nginx:/usr/share/nginx/html:ro
