services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1.12
    container_name: opengist
    restart: unless-stopped
    ports:
      - "6157:6157"
    volumes:
      - /opt/stacks/opengist:/opengist
