name: casaos
services:
  casa:
    container_name: casa
    image: dockurr/casa
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8083"
        protocol: tcp
    restart: always
    stop_grace_period: 1m0s
    volumes:
      - type: bind
        source: /opt/stacks/casaos
        target: /DATA
        bind:
          create_host_path: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
networks:
  default:
    name: casaos_default
