name: apache
services:
  web:
    container_name: apache-php
    environment:
      TZ: Asia/Kuala_Lumpur
    image: php:8.3-apache
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /opt/stacks/apache
        target: /var/www/html
        bind:
          create_host_path: true
networks:
  default:
    name: apache_default
