services:
  web:
    image: php:8.3-apache
    container_name: apache
    restart: unless-stopped
    environment:
      - TZ=Asia/Kuala_Lumpur
    ports:
      - "80:80"
    volumes:
      - /opt/stacks/apache:/var/www/html
